version: "3.8"

services:
  db:
    image: mariadb:10
    ports:
        - "3306:3306"
    volumes:
        - "tbb_mariadb_data:/var/lib/mysql"
    environment:
        - MYSQL_ROOT_PASSWORD=wordpress
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress

  redis:
    image: redis:alpine
    restart: always
    container_name: tbb_redis
    ports:
      - 6379:6379

volumes:
  tbb_mariadb_data:
