version: "3.8"

services:
  db:
    image: mariadb:10
    ports:
        - "3306:3306"
    volumes:
        - "tbb_mariadb_data:/var/lib/mysql"
    environment:
        - MYSQL_ROOT_PASSWORD=tbb
        - MYSQL_DATABASE=tbb
        - MYSQL_USER=tbb
        - MYSQL_PASSWORD=tbb

volumes:
  tbb_mariadb_data:
