version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: tbb_postgres
    restart: always
    volumes:
      - "tbb_postgresql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: tbb
      POSTGRES_USER: tbb
      POSTGRES_PASSWORD: tbb
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    container_name: tbb_redis
    ports:
      - 6379:6379

volumes:
  tbb_postgresql_data:
